# Keep the component-manager cache untouched. Compile a generated copy with a
# bounded scheduling margin for the short NAND read BUSY timeout (was ~2 ms).
idf_component_get_property(nand_dir espressif__spi_nand_flash COMPONENT_DIR)
idf_component_get_property(nand_lib espressif__spi_nand_flash COMPONENT_LIB)
set(nand_source "${nand_dir}/src/nand_impl.c")
set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${nand_source}")
file(READ "${nand_source}" nand_text)
set(old_timeout "if (timeout_ms == 0) {\n        timeout_ms = 1;\n    }")
set(new_timeout "if (timeout_ms < 20) {\n        timeout_ms = 20; /* scheduling margin, not an unconditional delay */\n    }")
string(FIND "${nand_text}" "${old_timeout}" timeout_pos)
if(timeout_pos EQUAL -1)
    message(FATAL_ERROR "NAND wait_for_ready changed; review recorder BUSY timeout adaptation")
endif()
string(REPLACE "${old_timeout}" "${new_timeout}" nand_text "${nand_text}")
# Re-read status before declaring timeout: the prior BUSY sample can be stale
# after preemption by the ADC/display task.
set(old_check "if ((xTaskGetTickCount() - start_tick) >= timeout_ticks) {")
set(new_check "${old_check}\n            ESP_RETURN_ON_ERROR(spi_nand_read_register(dev, REG_STATUS, &status), TAG, \"final BUSY check\");\n            if ((status & STAT_BUSY) == 0) {\n                if (status_out) *status_out = status;\n                return ESP_OK;\n            }")
string(FIND "${nand_text}" "${old_check}" check_pos)
if(check_pos EQUAL -1)
    message(FATAL_ERROR "NAND BUSY deadline check changed; review recorder adaptation")
endif()
string(REPLACE "${old_check}" "${new_check}" nand_text "${nand_text}")
set(generated_nand "${CMAKE_BINARY_DIR}/recorder_nand_impl.c")
file(WRITE "${generated_nand}" "${nand_text}")
get_target_property(nand_sources ${nand_lib} SOURCES)
set(patched_sources)
set(replaced FALSE)
foreach(src IN LISTS nand_sources)
    if(src MATCHES "(^|/)nand_impl\\.c$")
        list(APPEND patched_sources "${generated_nand}")
        set(replaced TRUE)
    else()
        list(APPEND patched_sources "${src}")
    endif()
endforeach()
if(NOT replaced)
    message(FATAL_ERROR "Cannot locate NAND implementation in component target")
endif()
set_property(TARGET ${nand_lib} PROPERTY SOURCES "${patched_sources}")
