# Short NAND commands/status/metadata transfers do not benefit from scheduling
# an SPI interrupt transaction. Bulk page transfers keep the existing DMA path.
idf_component_get_property(nand_dir espressif__spi_nand_flash COMPONENT_DIR)
idf_component_get_property(nand_lib espressif__spi_nand_flash COMPONENT_LIB)
set(nand_oper_source "${nand_dir}/src/spi_nand_oper.c")
set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${nand_oper_source}")
file(READ "${nand_oper_source}" oper_text)
set(old_transfer "esp_err_t ret = spi_device_transmit(handle->config.device_handle, (spi_transaction_t *) &e);")
set(new_transfer "esp_err_t ret;\n    if (transaction->miso_len <= 32 && transaction->mosi_len <= 32) {\n        ret = spi_device_polling_transmit(handle->config.device_handle, (spi_transaction_t *) &e);\n    } else {\n        ret = spi_device_transmit(handle->config.device_handle, (spi_transaction_t *) &e);\n    }")
string(FIND "${oper_text}" "${old_transfer}" oper_pos)
if(oper_pos EQUAL -1)
    message(FATAL_ERROR "NAND transaction implementation changed; review short-transaction optimization")
endif()
string(REPLACE "${old_transfer}" "${new_transfer}" oper_text "${oper_text}")
set(generated_oper "${CMAKE_BINARY_DIR}/recorder_spi_nand_oper.c")
file(WRITE "${generated_oper}" "${oper_text}")
get_target_property(nand_sources ${nand_lib} SOURCES)
set(patched_sources)
set(replaced FALSE)
foreach(src IN LISTS nand_sources)
    if(src MATCHES "(^|/)spi_nand_oper\\.c$")
        list(APPEND patched_sources "${generated_oper}")
        set(replaced TRUE)
    else()
        list(APPEND patched_sources "${src}")
    endif()
endforeach()
if(NOT replaced)
    message(FATAL_ERROR "Cannot locate NAND SPI operations in component target")
endif()
set_property(TARGET ${nand_lib} PROPERTY SOURCES "${patched_sources}")
